modLoader = "javafml"
loaderVersion = "[${javafml_loader_version_min},)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "lioloader"
version = "${version}"
displayName = "LioLoader"
authors = "Liopyu"
description = '''
A Global Datapack/Resourcepack Loader
'''

[[dependencies.lioloader]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version_min},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lioloader]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version_min},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lioloader]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version_min},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "lioloader.mixins.json"
logoFile="logo.png"
